# traject vars
# NOTE: the value of solr_replicate_master will determine whether the value of
# solr_url_to_index will be used for SOLR_REPLICATE_MASTER_URL (true) or SOLR_URL (false)
solr_replicate_master:  true
solr_url_to_index:      "{{ vault_solr_url_index }}"
# NOTE: only used if solr_replicate_main is true
solr_url_replica:         "{{ vault_solr_url }}"
traject_cron_minute:    30
traject_cron_hour:      18
traject_cron_weekday:   "1-5"
# NOTE: optional and mutually exclusive (only or (first &/or last))
#only_bib:               391566
#first_bib:              6270400
#last_bib:               6331099
#sanity_check_count:       10000
traject_cron_action:    "create" # create | remove | none (if absent, create is default)
